apiVersion: v1
kind: Service
metadata:
  name: node-grpc-server
  namespace: infranauts-meetup
spec:
  ports:
  - name: grpc
    port: 50051
    protocol: TCP
    targetPort: grpc
  selector:
    app: node-grpc-server
