---
apiVersion: v1
kind: Service
metadata:
  namespace: infranauts-meetup
  labels:
    app: node-grpc-client
  name: node-grpc-client
spec:
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
      nodePort: 30110
      protocol: TCP
  selector:
    app: node-grpc-client
  type: NodePort